repos:
- repo: https://github.com/igorshubovych/markdownlint-cli
  rev: v0.31.1
  hooks:
  - id: markdownlint
- repo: https://github.com/koalaman/shellcheck-precommit
  rev: v0.8.0
  hooks:
  -   id: shellcheck
